### PR TITLE
fix macos build

### LINKED ISSUE #551: macOS: Unknown type u_int, u_short, and u_char
When trying to build in macOS using the following commands:

```
meson setup _build -Dstemming=false -Dsystemd=false --buildtype=plain --auto-features=enabled --wipe
ninja -C _build
```

```
I am getting the following errors:
In file included from ../src/as-system-info.c:54:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:101:2: error: unknown type name 'u_int'
        u_int   cr_version;             /* structure layout version */
        ^
In file included from ../src/as-system-info.c:54:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:85:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:116:2: error: unknown type name 'u_int'
        u_int   p_estcpu;        /* Time averaged value of p_cpticks. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:121:2: error: unknown type name 'u_int'
        u_int   p_swtime;        /* Time swapped in or out. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:122:2: error: unknown type name 'u_int'
        u_int   p_slptime;       /* Time since last blocked. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:136:2: error: unknown type name 'u_char'
        u_char  p_priority;     /* Process priority. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:137:2: error: unknown type name 'u_char'
        u_char  p_usrpri;       /* User-priority based on p_cpu and p_nice. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:142:2: error: unknown type name 'u_short'
        u_short p_xstat;        /* Exit status for wait; also stop signal. */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/proc.h:143:2: error: unknown type name 'u_short'
        u_short p_acflag;       /* Accounting flags. */
```

It looks like as-system-info.c is including sys/types.h which should have those definitions, prior to including sys/sysctl.h. sysctl.h is including ucred.h and proc.h with those types giving the errors.

macOS Sonoma 14.1 on Apple M1 Pro
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### PR DESCRIPTION
**Pull request by chenrui333**
closes #551

relates to homebrew/homebrew-core#154003

### CODE REVIEW

**Comment by ximion** [comment]
Are those defined in a header somehow that is missing and should be included? Or is defining these types manually common practice?
It feels a bit weird to do that, but if that's normal for Apple builds then it's definitely fine :-)

**Comment by chenrui333** [comment]
> Are those defined in a header somehow that is missing and should be included? Or is defining these types manually common practice? It feels a bit weird to do that, but if that's normal for Apple builds then it's definitely fine :-)

yeah, it is pretty normal for macos builds. (I think those type definitions only avail in linux builds)

**Comment by ximion** [comment]
Extremely weird (would have expected this to be defined in some Apple header), but fair enough!
Thank you for the patch!

**Comment by dehesselle** [comment]
This is indeed not the correct approach to fix this (no offense). You need to run meson with `-Dc_args=-D_DARWIN_C_SOURCE` and then you get the defines via Apple provided headers.

**Comment by ximion** [comment]
Can you submit a new PR for that, adding a snippet to the `meson.build` file that adds this flag if macOS is detected? That would make it automatic for Mac users.

**Pull request merged**
