### PR TITLE
Add COSMIC to xdg-category-names.txt

### PR DESCRIPTION
**Pull request by jackpot51**
COSMIC is a desktop environment and a valid category name as part of the specification: https://specifications.freedesktop.org/menu-spec/latest/additional-category-registry.html

### CODE REVIEW

**Comment by jackpot51** [comment]
@ximion I would strongly request that COSMIC is not filtered our of the metadata as "low quality", we are going to use it to show applications and applets specifically made for the platform.

**Comment by razzeee** [comment]
I would recommend using keywords

**Comment by razzeee** [comment]
Related https://github.com/flathub-infra/website/issues/3201

**Comment by ximion** [comment]
> @ximion I would strongly request that the COSMIC category is not filtered out of the metadata as "low quality", we are going to use it to show applications and applets specifically made for the platform.

We will phase out *all* desktop and toolkit specific categories in the near future, and I am quite against adding even more. If you want to filter things by a project/organization, you can use https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_group

**Comment by jackpot51** [comment]
Ok, I will recommend using project_group. My concern with that is that it only allows one value.

**Comment by jackpot51** [comment]
> We will phase out all desktop and toolkit specific categories in the near future, and I am quite against adding even more

Where is this being discussed? COSMIC is part of the spec now so it does not seem valid to refuse to include it.

**Comment by razzeee** [comment]
All other DEs are also filtered afaik

**Comment by jackpot51** [comment]
We have come up with an alternative.

**Pull request closed without merging**
