### PR TITLE
Some random meson improvements

### PR DESCRIPTION
**Pull request by tristan957**
Adding overrides is the biggest thing.

### CODE REVIEW

**Comment by ximion** [comment]
Enabling fatal warnings may not have been such a good idea ;-)
(I explicitly want to add more strict warning flags when building in maintainer mode, but build with relaxed options in production, so GCC updates do not cause sudden mass build failures when a new warning was added. Meson unfortunately doesn't allow this scheme and goes for an "always or never" approach, which I don't think is good at all. If there's a way to achieve the same result with Meson though, that would be fine with me.)

**Comment by tristan957** [comment]
Should I fix this `-Werror` warning?

**Comment by tristan957** [comment]
I don't see a reason to ever let Meson warn, honestly. Compiler warnings like "-Wdecl-after-statement" can get annoying when doing random things however.

**Comment by ximion** [comment]
> Should I fix this `-Werror` warning?

Only if the current behavior is retained: All warnings enabled + `-Werror` when in maintainer mode, no `-Werror` when building without maintainer mode.
Right now, I see no other way to do that than to remove the added `--fatal-meson-warnings`, but if you know a better solution, I'd be happy for that!

**Comment by ximion** [comment]
> Compiler warnings like "-Wdecl-after-statement" can get annoying when doing random things however.

If you're not in maintainer mode, that's just a warning and not an error. It will become one if you try to upstream the changes though.

**Comment by tristan957** [comment]
I'm just giving an example of how CIs should enforce -Werror, not build systems.

**Comment by ximion** [comment]
I do not understand what you mean. The CI does enforce -Werror, it is not enabled by default.

**Comment by ximion** [comment]
If you drop the `--fatal-meson-warnings` change for now (until Meson is changed to allow to conditionally enable warnings using a native method), this change is good to go and should also pass CI.

**Comment by ximion** [comment]
I've merged all the changes except for the CI-breaking one. Thank you for the patch!

**Pull request closed without merging**
