### PR TITLE
Add an <internet/> kind to requires/recommends/supports /3

### PR DESCRIPTION
**Pull request by ximion**
This is a version of https://github.com/ximion/appstream/pull/425 with some minor fixes and added validation.

### CODE REVIEW

**Comment by JakobDev** [comment]
Maybe you should also add a example for offline-only, so they User know in which relations-tag he should put it.

**Comment by ximion** [comment]
This is shaping up to be the most extensive example block in the whole specification :-D - I normally like to keep the examples quite brief, as information should be derivable from the text, but I also do see the point here of adding an example for it in a `supports` block for even more clarity.

**Comment by JakobDev** [comment]
I found this in the documentation as exmaple:
```xml
<!-- never uses the internet, even if available -->
<requires>
  <internet>never</internet>
</requires>
```
This is invalid and should be offline-only.

**Comment by ximion** [comment]
Ha! Well spotted! Thanks for having another look, it's good to not make a release with these obvious but very confusing errors (and I didn't spot that when reviewing the original PR!)

**Pull request merged**
