### PR TITLE
Update ru.po

### PR DESCRIPTION
**Pull request by gostsdmitry**

### CODE REVIEW

**Comment by tintou** [comment]
The AppStream project is using Weblate to manage its translations: https://hosted.weblate.org/projects/appstream

**Comment by gostsdmitry** [comment]
> The AppStream project is using Weblate to manage its translations: https://hosted.weblate.org/projects/appstream

Sorry! I don't have an account on this site yet...

**Comment by ximion** [comment]
> Sorry! I don't have an account on this site yet...

As said before, you could just login via your GitHub account, there is no need to register at Weblate separately :-)
I will merge this later, merging translations manually requires some care to not risk merge conflicts with translations submitted via Weblate.

**Comment by gostsdmitry** [comment]
Consideration of this PR is no longer required, so I am closing it.

**Comment by ximion** [comment]
Nice, I see this landed automatically via Weblate!
Thank you for helping with translation! :-)

**Pull request closed without merging**
