### PR TITLE
Reduce source incompatibility against last version

### PR DESCRIPTION
**Pull request by aleixpol**
Makes it possible to have something like this:
https://phabricator.kde.org/D3265

### CODE REVIEW

**Comment by ximion** [comment]
Is this really not solveable in the Discover branch is a reasonable way? (esp. the enum aliasing...)

**Comment by ximion** [comment]
At Debian we are using this patch to build with more recent AppStream releases: https://anonscm.debian.org/git/pkg-kde/plasma/plasma-discover.git/tree/debian/patches/01_new-appstreamqt.patch
So far this seems to work well, but I haven't tested yet if this also works with older AS versions (otherwise I would have submitted it for review).
The patch is based from the one you have under review at Phab at time.

**Comment by aleixpol** [comment]
Closing and moving the ifdefing to Discover.

**Comment by aleixpol** [comment]
Wait, we'll still need something to find the AppStreamConfig.cmake, do you also want us to try both?

**Comment by ximion** [comment]
In the patch linked above I simply tried both and emitted an error if none was found.
Not super pretty, but effective.

I very much want to get rid of the old name and API, if we re-add this to AppStream now, this means we will need to support this for a very long time again, if we don't want to break older Discover versions. By not reintroducing it, we can be sure Discover uses the new API and names when linked to the latest AppStream lib.

**Comment by rdieter** [comment]
fwiw, I tried using the aforementioned debian patch on my fedora box... and plasma discover crashes pretty soon after browsing packages for a minute or 2.

**Comment by ximion** [comment]
Thanks for the hint - did you try that with the current AppStream version?
I'll try a longer-running Plasma Discover session today, maybe I can reproduce this issue.

**Comment by aleixpol** [comment]
I pushed it to Plasma/5.8, please test that.

**Pull request closed without merging**
