### PR TITLE
Fixed VAPI compilation.

### PR DESCRIPTION
**Pull request by tintou**
The .gir filename was wrong.

### CODE REVIEW

**Comment by ximion** [comment]
Thanks!

**Comment by tintou** [comment]
I've seen that you're the debian maintainer. Would you mind shipping the .vapi file with the -dev package in next releases ?

**Comment by ximion** [comment]
Yes, I can do that (was originally disabled due to a vapigen bug, looks like I forgot to enable it again....)
Expect an upload today :)

**Comment by ximion** [comment]
The Vala API is now available in Debian as well.

**Pull request merged**
