### PR TITLE
sysinfo: Add memory size detection support for GNU/Hurd

### PR DESCRIPTION
**Pull request by pinotree**

### CODE REVIEW

**Comment by pinotree** [comment]
@sthibaul while this seems to work, would you please take a look in case I'm doing anything wrong? thanks!

**Comment by ximion** [comment]
It looks sensible to me (but I know nothing about Hurd), so, is this safe to merge in your opinion?

**Comment by sthibaul** [comment]
Yes, it's good to merge

**Comment by ximion** [comment]
Nice, thank you! :-)

**Pull request merged**
